### ISSUE TITLE
Add setting to turn off pop-up

### ISSUE THREAD

**Issue by SamZoia** [rafaelgssa/container-bookmarks#3]
Good job with this extension.
I would like for a feature to be implemented.
When you add a bookmark, the extension automatically opens a popup to let you configure it.
In my opinion and usage case the process of adding bookmark has to be snappy, but the popup slows it down a lot.
This trade off is not worth it in my normal usage, so I think that you could add an option to disable this pop-up and let the user modify the bookmark when needed with the option in the contextual menu.
Thanks

**Comment by rafaelgssa** [comment]
v1.1.0 allows you to turn off the popup. Sorry it took so long.
